import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { UserContextProvider } from "./contexts/userContext";
import "./globals.css";
import { DiaryContextProvider } from "./contexts/diaryContext";

const poppins = Poppins({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserContextProvider>
        <DiaryContextProvider>
          <body className={poppins.className}>{children}</body>
        </DiaryContextProvider>
      </UserContextProvider>
    </html>
  );
}
