import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { UserContextProvider } from "./contexts/userContext";
import "./globals.css";
import { DiaryContextProvider } from "./contexts/diaryContext";
import { CounsellorProvider } from "./contexts/counsellorContext";
import "@chatscope/chat-ui-kit-styles/dist/default/styles.min.css";
import { Toaster } from "react-hot-toast";

const poppins = Poppins({ weight: "300", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Toaster />
      <UserContextProvider>
        <DiaryContextProvider>
          <CounsellorProvider>
            <body className={poppins.className}>{children}</body>
          </CounsellorProvider>
        </DiaryContextProvider>
      </UserContextProvider>
    </html>
  );
}
